### ISSUE TITLE
clsx regex first part doesn't capture the whole group

### ISSUE THREAD

**Issue by abhinnankit** [paolotiu/tailwind-intellisense-regex-list#20]
CLSX's regex first part doesn't capture the whole group if there is another ')' present. For eg:

`clsx('focus:shadow-[0_0_15px_0_rgba(0,0,0,0.1)]')`

`clsx\\(([^)]*)\\)` will only capture `clsx('focus:shadow-[0_0_15px_0_rgba(0,0,0,0.1)`.
Here is the regex in action - [Current clsx regex](https://regexr.com/7l0hm)

To capture the whole group we need to update the regex to `clsx\\(([^]*)\\)`

Here is the regex in action - [Modified clsx regex](https://regexr.com/7l0hp)

**Comment by paolotiu** [comment]
Thanks for this!

**Comment by DasOhmoff** [comment]
Hey, I was trying to understand this regex, but I don't think this regex is valid is it? According to my understanding, it seems that the part `[^]*` in the regex is wrong. (Even tools such as https://regex101.com/ see it as an error). Previously there was a `)` which meant sense, because it meant to match all characters expect a `)`. Now it would mean to match all characters expect `` (empty, there is nothing there), which in essence would mean that it is the same thing as `.*` - probably javascript just interprets it as that. Which would be an issue because it would mean that it matches everything after `clsx(`, whether its within the function or outside of it.

Maybe I am wrong, please clarify if that is the case. Thanks :)

**Comment by DasOhmoff** [comment]
See here how it matches stuff outside of it:
![image](https://github.com/paolotiu/tailwind-intellisense-regex-list/assets/16063186/2b48b58f-3ff5-4208-8576-3ff3c3706f57)

**Comment by abhinnankit** [comment]
It is actually matching everything inside of `clsx(` and `)`, and yeah `[^]*` is essentially `.*`. Feel free to update it. Please be sure to accommodate `clsx('focus:shadow-[0_0_15px_0_rgba(0,0,0,0.1)]')`, since it is a valid use case.

PS: I am no regex expert.

**Comment by abhinnankit** [comment]
clsx\(.*?\)(?!\])
This should work for both of our cases.
